[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$InputFile,

    [string]$OutJson = "..\examples\correlation-output.json",

    [switch]$WriteTicketFiles,

    [int]$OfflineThresholdMinutes = 60
)

if (-not (Test-Path $InputFile)) {
    Write-Error "Input file not found: $InputFile"
    exit 2
}

# Read JSON (single object OR array)
$jsonText = Get-Content -Path $InputFile -Raw
$data = $jsonText | ConvertFrom-Json

# Normalize to array
$devices = @()
if ($data -is [System.Collections.IEnumerable] -and -not ($data -is [string])) {
    $devices = @($data)
} else {
    $devices = @($data)
}

function Get-DeviceField {
    param(
        $device,
        [string]$name
    )
    if ($device -and ($device.PSObject.Properties.Name -contains $name)) {
        return $device.$name
    }
    return $null
}

function Set-EscalationIfHigher {
    param(
        [System.Collections.IDictionary]$Correlation,
        [string]$NewEscalation
    )

    $rank = @{
        "None" = 0
        "NOC - Investigate Offline" = 1
        "NOC - Backup Review" = 2
        "NOC - Disk Remediation" = 3
        "NOC - Critical Backup Impact" = 4
        "SOC - Review" = 5
        "SOC - Critical" = 6
    }

    $current = $Correlation.Escalation
    if (-not $rank.ContainsKey($current)) { $current = "None" }
    if (-not $rank.ContainsKey($NewEscalation)) { return }

    if ($rank[$NewEscalation] -gt $rank[$current]) {
        $Correlation.Escalation = $NewEscalation
    }
}


function New-ConnectWiseNoteLines {
    param(
        [Parameter(Mandatory=$true)]
        $ResultObject,

        [string]$JsonArtifactName = "correlation-output.json"
    )

    $r = $ResultObject

    $lines = @()
    $lines += "=== Correlation Summary (POC) ==="
    $lines += ("Device: {0}" -f $r.DeviceName)
    $lines += ("Client: {0}" -f $r.Client)
    if ($r.Site)       { $lines += ("Site: {0}" -f $r.Site) }
    if ($r.DeviceType) { $lines += ("Type: {0}" -f $r.DeviceType) }
    if ($r.IPAddress)  { $lines += ("IP: {0}" -f $r.IPAddress) }
    if ($r.LoggedOnUser) { $lines += ("User: {0}" -f $r.LoggedOnUser) }
    if ($r.LastSeenUtc)  { $lines += ("LastSeenUtc: {0}" -f $r.LastSeenUtc) }

    $lines += ""
    $lines += ("Status: {0}" -f $r.Correlation.Status)
    $lines += ("Escalation: {0}" -f $r.Correlation.Escalation)
    $lines += ("Priority: {0} | Board: {1}" -f $r.Ticket.Priority, $r.Ticket.Board)
    $lines += ("RemediationAllowed: {0}" -f $r.Correlation.RemediationAllowed)

    if ($r.EDR -and ($r.EDR.PSObject.Properties.Name -contains "IsQuarantined")) {
        $lines += ("EDR Quarantined: {0}" -f $r.EDR.IsQuarantined)
        if ($r.EDR.QuarantineReason)   { $lines += ("EDR Reason: {0}" -f $r.EDR.QuarantineReason) }
        if ($r.EDR.QuarantineSinceUtc) { $lines += ("EDR Since: {0}" -f $r.EDR.QuarantineSinceUtc) }
    }

    if ($r.Backup -and $r.Backup.Status) {
        $prod = $r.Backup.Product
        if (-not $prod) { $prod = "Backup" }
        $lines += ("{0} Status: {1}" -f $prod, $r.Backup.Status)
        if ($r.Backup.LastRunUtc) { $lines += ("Backup LastRunUtc: {0}" -f $r.Backup.LastRunUtc) }
    }

    $lines += ""
    $lines += "Notes:"
    if ($r.Correlation.Notes.Count -eq 0) {
        $lines += "- (none)"
    } else {
        foreach ($n in $r.Correlation.Notes) { $lines += "- $n" }
    }

    $lines += ""
    $lines += "Evidence:"
    $lines += ("- {0} (attached)" -f $JsonArtifactName)
    $lines += "- Generated by SOC-Correlation.ps1 (POC)"

    return $lines
}

function Get-CorrelationSummary {
    param($device)

    # ---------- Support both schemas ----------
    $edrObj     = Get-DeviceField -device $device -name "EDR"
    $metricsObj = Get-DeviceField -device $device -name "Metrics"
    $backupObj  = Get-DeviceField -device $device -name "Backup"

    # Quarantine
    $isQuarantined = $false
    if ($edrObj -and ($edrObj.PSObject.Properties.Name -contains "IsQuarantined") -and $null -ne $edrObj.IsQuarantined) {
        $isQuarantined = [bool]$edrObj.IsQuarantined
    } else {
        $legacyQuarantine = Get-DeviceField -device $device -name "IsQuarantined"
        if ($null -ne $legacyQuarantine) { $isQuarantined = [bool]$legacyQuarantine }
    }

    # Online (prefer legacy IsOnline; else infer via LastSeenUtc)
    $isOnline = $true
    $legacyOnline = Get-DeviceField -device $device -name "IsOnline"
    if ($null -ne $legacyOnline) {
        $isOnline = [bool]$legacyOnline
    } else {
        $lastSeenUtc = Get-DeviceField -device $device -name "LastSeenUtc"
        if ($lastSeenUtc) {
            try {
                $lastSeen = [datetime]::Parse($lastSeenUtc).ToUniversalTime()
                $isOnline = ((((Get-Date).ToUniversalTime() - $lastSeen).TotalMinutes) -le $OfflineThresholdMinutes)
            } catch {
                $isOnline = $true
            }
        }
    }

    # Metrics
    $diskFree = $null
    $cpuPct   = $null
    if ($metricsObj) {
        if ($metricsObj.PSObject.Properties.Name -contains "DiskFreeGB") { $diskFree = $metricsObj.DiskFreeGB }
        if ($metricsObj.PSObject.Properties.Name -contains "CPUPercent") { $cpuPct = $metricsObj.CPUPercent }
    } else {
        $diskFree = Get-DeviceField -device $device -name "DiskFreeGB"
        $cpuPct   = Get-DeviceField -device $device -name "CPUPercent"
    }

    # Backup (v3 schema or legacy flat fields)
    $backupStatus = $null
    $backupLastRunUtc = $null
    $backupProduct = $null

    if ($backupObj) {
        if ($backupObj.PSObject.Properties.Name -contains "Status")     { $backupStatus = $backupObj.Status }
        if ($backupObj.PSObject.Properties.Name -contains "LastRunUtc") { $backupLastRunUtc = $backupObj.LastRunUtc }
        if ($backupObj.PSObject.Properties.Name -contains "Product")    { $backupProduct = $backupObj.Product }
    } else {
        $backupStatus = Get-DeviceField -device $device -name "BackupStatus"
        $backupLastRunUtc = Get-DeviceField -device $device -name "BackupLastRunUtc"
        $backupProduct = Get-DeviceField -device $device -name "BackupProduct"
    }

    # ---------- Correlation output ----------
    $correlation = [ordered]@{
        Statuses           = @()
        Status             = "Normal"
        Escalation         = "None"
        Notes              = @()
        Severity           = 0   # 0=OK, 1=Warn, 2=Critical
        RemediationAllowed = $true
    }

    # Rule A/B: Quarantine first (suppresses remediation)
    if ($isQuarantined) {
        $correlation.Statuses += "Quarantined"
        $correlation.RemediationAllowed = $false

        if (-not $isOnline) {
            Set-EscalationIfHigher -Correlation $correlation -NewEscalation "SOC - Critical"
            $correlation.Notes += "Device is quarantined AND appears offline (RMM last seen stale). Immediate SOC visibility required."
            $correlation.Severity = 2
        } else {
            Set-EscalationIfHigher -Correlation $correlation -NewEscalation "SOC - Review"
            $correlation.Notes += "Device is quarantined but still appears online."
            $correlation.Severity = [math]::Max($correlation.Severity, 1)
        }

        # Optional clarity: quarantine suppresses automation/remediation even if other issues exist
        if ($backupStatus -eq "Failed") {
            $correlation.Notes += "Backup indicates failure, but remediation/actions are suppressed due to quarantine state (SOC ownership)."
        }
        if ($null -ne $diskFree -and [double]$diskFree -lt 5) {
            $correlation.Notes += "Disk is low, but remediation/actions are suppressed due to quarantine state (SOC ownership)."
        }
    }

    # Rule D: Disk critical (only if not quarantined)
    if (-not $isQuarantined -and $null -ne $diskFree -and [double]$diskFree -lt 5) {
        $correlation.Statuses += "DiskCritical"
        Set-EscalationIfHigher -Correlation $correlation -NewEscalation "NOC - Disk Remediation"
        $correlation.Notes += "Low disk space detected (<5 GB)."
        $correlation.Severity = [math]::Max($correlation.Severity, 1)
    }

    # Rule E: Backup failure (only if not quarantined)
    if (-not $isQuarantined -and $backupStatus -eq "Failed") {
        $correlation.Statuses += "BackupFailed"

        if (-not $isOnline) {
            Set-EscalationIfHigher -Correlation $correlation -NewEscalation "NOC - Critical Backup Impact"
            $correlation.Notes += "Backup failed and device appears offline."
            $correlation.Severity = [math]::Max($correlation.Severity, 2)
        } else {
            if ($correlation.Escalation -eq "None") {
                $correlation.Escalation = "NOC - Backup Review"
            }
            if ($backupLastRunUtc) {
                $correlation.Notes += ("Latest backup job reported failed. LastRunUtc: {0}" -f $backupLastRunUtc)
            } else {
                $correlation.Notes += "Latest backup job reported failed."
            }
            $correlation.Severity = [math]::Max($correlation.Severity, 1)
        }
    }

    # Rule C: Offline only (only if not quarantined)
    if (-not $isQuarantined -and -not $isOnline) {
        $correlation.Statuses += "Offline"
        if ($correlation.Escalation -eq "None") {
            Set-EscalationIfHigher -Correlation $correlation -NewEscalation "NOC - Investigate Offline"
        }
        $correlation.Notes += "Device appears offline without quarantine. Begin standard offline-agent workflow."
        $correlation.Severity = [math]::Max($correlation.Severity, 1)
    }

    # Build combined status string
    if ($correlation.Statuses.Count -gt 0) {
        $correlation.Status = ($correlation.Statuses | Select-Object -Unique) -join "+"
    } else {
        $correlation.Status = "Normal"
    }

    # Priority/Board (PS 5.1 compatible)
    $priority = "P4"
    if ($correlation.Severity -eq 2) { $priority = "P1" }
    elseif ($correlation.Severity -eq 1) { $priority = "P2" }

    $board = "N/A"
    if ($correlation.Escalation -like "SOC*") { $board = "SOC" }
    elseif ($correlation.Escalation -like "NOC*") { $board = "NOC" }

    # Output object
    $out = [ordered]@{
        DeviceName   = (Get-DeviceField $device "DeviceName")
        Client       = (Get-DeviceField $device "Client")
        Site         = (Get-DeviceField $device "Site")
        DeviceType   = (Get-DeviceField $device "DeviceType")
        LastSeenUtc  = (Get-DeviceField $device "LastSeenUtc")
        OsVersion    = (Get-DeviceField $device "OsVersion")
        IPAddress    = (Get-DeviceField $device "IPAddress")
        LoggedOnUser = (Get-DeviceField $device "LoggedOnUser")

        EDR     = $edrObj
        Metrics = $metricsObj
        Backup  = $backupObj

        Correlation  = $correlation
        Ticket       = [ordered]@{
            System   = "ConnectWise Manage"
            Priority = $priority
            Board    = $board
            Summary  = ("{0} - {1} - {2}" -f (Get-DeviceField $device "DeviceName"), $correlation.Status, $correlation.Escalation)
        }
    }

    # If old schema had no EDR/Metrics/Backup objects, preserve legacy values for consistency
    if (-not $out.EDR) {
        $out.EDR = [ordered]@{
            IsQuarantined      = $isQuarantined
            QuarantineReason   = (Get-DeviceField $device "QuarantineReason")
            QuarantineSinceUtc = (Get-DeviceField $device "QuarantineSinceUtc")
        }
    }
    if (-not $out.Metrics) {
        $out.Metrics = [ordered]@{
            DiskFreeGB  = $diskFree
            CPUPercent  = $cpuPct
        }
    }
    if (-not $out.Backup) {
        $out.Backup = [ordered]@{
            Product    = $backupProduct
            Status     = $backupStatus
            LastRunUtc = $backupLastRunUtc
        }
    }

    return [pscustomobject]$out
}

$results = foreach ($d in $devices) { Get-CorrelationSummary -device $d }

# Ensure examples dir exists and save JSON output (portfolio artifact)
$examplesDir = Join-Path $PSScriptRoot "..\examples"
if (-not (Test-Path $examplesDir)) { New-Item -Path $examplesDir -ItemType Directory -Force | Out-Null }
$outPath = Join-Path $PSScriptRoot $OutJson
$results | ConvertTo-Json -Depth 12 | Set-Content -Path $outPath -Encoding UTF8

# Console summary table
Write-Host ""
Write-Host "=== Correlation Summary ==="
$results |
    Select-Object `
        DeviceName,
        @{n="Status";e={$_.Correlation.Status}},
        @{n="Escalation";e={$_.Correlation.Escalation}},
        @{n="Severity";e={$_.Correlation.Severity}},
        @{n="Remediate";e={$_.Correlation.RemediationAllowed}} |
    Format-Table -AutoSize

# Ticket-ready summaries (only non-OK)
$nonOk = $results | Where-Object { $_.Correlation.Severity -gt 0 }
if ($nonOk.Count -gt 0) {
    Write-Host ""
    Write-Host "=== Ticket Notes (Non-OK) ==="
    foreach ($r in $nonOk) {

        Write-Host "`n--- Ticket Summary ---"
        Write-Host "Device: $($r.DeviceName)"
        Write-Host "Client: $($r.Client)"
        if ($r.Site) { Write-Host "Site: $($r.Site)" }
        Write-Host "Status: $($r.Correlation.Status)"
        Write-Host "Escalation: $($r.Correlation.Escalation)"
        Write-Host "Priority: $($r.Ticket.Priority) | Board: $($r.Ticket.Board)"
        Write-Host "RemediationAllowed: $($r.Correlation.RemediationAllowed)"
        if ($r.Backup -and $r.Backup.Status) {
            $prod = $r.Backup.Product
            if (-not $prod) { $prod = "Backup" }
            Write-Host ("{0} Status: {1}" -f $prod, $r.Backup.Status)
        }
        Write-Host "Notes:"
        if ($r.Correlation.Notes.Count -eq 0) { Write-Host "- (none)" }
        else { $r.Correlation.Notes | ForEach-Object { Write-Host "- $_" } }

        if ($WriteTicketFiles) {
            $ticketDir = Join-Path $PSScriptRoot "..\examples\ticket-notes"
            if (-not (Test-Path $ticketDir)) { New-Item -Path $ticketDir -ItemType Directory -Force | Out-Null }
            $safeName = ($r.DeviceName -replace '[^\w\-]','_')
            $ticketPath = Join-Path $ticketDir ("ticket-note-{0}.txt" -f $safeName)

            $noteLines = New-ConnectWiseNoteLines -ResultObject $r -JsonArtifactName "correlation-output.json"
            $noteLines -join "`r`n" | Set-Content -Path $ticketPath -Encoding UTF8
        }
    }
} else {
    Write-Host "`nAll devices OK. No ticket notes generated."
}

Write-Host ""
Write-Host "=== Director Snapshot (POC) ==="
$total    = @($results).Count
$critical = @($results | Where-Object { $_.Correlation.Severity -eq 2 }).Count
$warning  = @($results | Where-Object { $_.Correlation.Severity -eq 1 }).Count
$ok       = @($results | Where-Object { $_.Correlation.Severity -eq 0 }).Count

Write-Host ("Total Devices: {0}" -f $total)
Write-Host ("Critical: {0}" -f $critical)
Write-Host ("Warning: {0}" -f $warning)
Write-Host ("OK: {0}" -f $ok)
Write-Host ("Artifacts: examples\correlation-output.json, examples\ticket-notes\")



Write-Host "`nJSON output saved to: $outPath"

# Exit code = worst severity (PS 5.1 safe)
$maxSeverity = 0
foreach ($r in $results) { $maxSeverity = [math]::Max($maxSeverity, [int]$r.Correlation.Severity) }
exit $maxSeverity
```
